EXTENSION_TO_FOLDER = {
    'Images': ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'svg', 'ico', 'heic', 'raw', 'cr2', 'nef'],
    'Music': ['mp3', 'wav', 'aac', 'flac', 'ogg', 'm4a', 'wma', 'alac'],
    'Videos': ['mp4', 'avi', 'mkv', 'mov', 'wmv', 'flv', 'webm', 'mpeg', '3gp'],
    'Documents': ['txt', 'pdf', 'odt', 'rtf', 'gdoc', 'md', 'tex', 'log'],
    'Programs': ['exe', 'bat', 'sh', 'app', 'msi', 'jar', 'py', 'java', 'cs', 'cpp', 'c', 'swift', 'go', 'php', 'rb', 'ts', 'rs'],
    'Compressed': ['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'xz'],
    'Web Files': ['html', 'css', 'php', 'xml', 'aspx', 'jsp', 'htm', 'xhtml'],
    'Adobe Suite': ['psd', 'ai', 'indd', 'prproj', 'aep', 'xd', 'fla', 'svgz'],
    'Microsoft Office': ['docx', 'doc', 'xlsx', 'xls', 'pptx', 'ppt', 'one', 'accdb', 'pub', 'vsdx'],
    '3D Models': ['blend', 'fbx', 'obj', 'stl', 'dae', '3ds', 'ply', 'glb', 'gltf', 'max', 'x3d'],
    'Data Files': ['csv', 'sqlite', 'db', 'sql', 'parquet', 'hdf5', 'sav', 'dta', 'sas7bdat'],
    'Configuration': ['env', 'ini', 'cfg', 'toml', 'yaml', 'yml', 'plist'],
    'Font Files': ['ttf', 'otf', 'woff', 'woff2', 'eot', 'pfb', 'pfm'],
    'eBooks': ['epub', 'mobi', 'azw3', 'lit', 'fb2'],
    'Design Files': ['sketch', 'xd', 'fig', 'afdesign', 'afphoto', 'afpub'],
    'Gaming Assets': ['unity', 'asset', 'pak', 'uasset', 'utx', 'pck'],
    'CAD Files': ['dwg', 'dxf', 'step', 'stp', 'iges', 'ipt', 'sldprt'],
    'Virtual Machines': ['vmdk', 'vdi', 'vhd', 'ova', 'ovf'],
    'Backup Files': ['bak', 'bkp', 'backup'],
    'Scripts': ['sh', 'bash', 'ps1', 'cmd', 'rb', 'pl'],
    'Audio Projects': ['flp', 'als', 'logicx', 'cpr', 'ptx', 'aup3'],
    'Video Projects': ['veg', 'pproj', 'drp', 'fcpxml'],
    'Disk Images': ['iso', 'dmg', 'img', 'bin', 'cue'],
    'Photoshop Files': ['psd', 'psb'],
    'Illustrator Files': ['ai', 'ait', 'eps'],
    'Premiere Pro Files': ['prproj'],
    'After Effects Files': ['aep', 'aepx'],
    'Blender Files': ['blend'],
    'Maya Files': ['ma', 'mb'],
    'Unity Files': ['unity', 'asset', 'prefab'],
    'Unreal Engine Files': ['uasset', 'umap', 'pak'],
    'Logic Pro Files': ['logicx'],
    'Final Cut Pro Files': ['fcpxml', 'fcpbundle'],
    'Ableton Live Files': ['als'],
    'FL Studio Files': ['flp'],
    'Pro Tools Files': ['ptx'],
    'SAS Files': ['sas', 'sas7bdat', 'sasxport'],
    'SPSS Files': ['sav', 'spo'],
    'STATA Files': ['dta'],
    'MATLAB Files': ['mat', 'm'],
    'Python Notebooks': ['ipynb'],
    'LaTeX Files': ['tex', 'bib'],
    'Markdown Files': ['md'],
    'JSON & XML Files': ['json', 'xml'],
    'Database Files': ['db', 'sqlite', 'sql', 'mdb'],
    'Docker Files': ['dockerfile', 'dockerignore'],
    'Kubernetes Files': ['yaml', 'yml'],
    'Virtual Reality': ['vrb', 'vrd', 'vrml'],
    'Augmented Reality': ['arproj', 'arscene'],
}